-- =========================================================================
-- VirSaa Gifts — Add "Personalised Woodwork"
-- Run this once in the Supabase SQL editor to sync an existing database.
-- Idempotent: safe to re-run (ON CONFLICT ... DO NOTHING).
-- =========================================================================

INSERT INTO public.categories (id, name, slug, description, icon) VALUES ('cat-personalised-woodwork', 'Personalised Woodwork', 'personalised-woodwork', 'Artisanal Eco Creations', 'Hammer') ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, sku, name, category_id, subcategory, price, gst_percent, description, specification, primary_use_case, secondary_use_cases, material_tags, tier, speed, featured, min_order_qty, collections) VALUES ('prod-ww-1', 'VG-WW-001', 'Brass-Inlaid Walnut Desk Plaque', 'cat-personalised-woodwork', 'Awards & Plaques', 1499, 18, 'A solid walnut plaque with a hand-set brass inlay, laser-engraved with names, insignia or messages — a personal milestone that outlives the event.', '{"dimensions":"6\" x 4\" x 0.75\", reclaimed walnut, brass inlay detail","weight":"Artisanal spec","finish":"Natural Waxed Timber","packaging":"Handcrafted Wooden Gift Box","customization_options":["Laser Name Engraving","Brass Inset Monogram","Custom Insignia","Bespoke Shaping"],"origin":"Artisan Clusters, India","eco_impact":"Reclaimed timber, zero single-use plastic, ethically sourced components"}'::jsonb, 'Awards & Recognition', ARRAY['Executive Gifting','Milestone Celebrations','Client Souvenirs','Desk Keepsakes']::TEXT[], ARRAY['Wood','Brass']::TEXT[], 'Signature'::product_tier, '3-5 Days'::speed_type, true, 10, ARRAY['Events & Recognition']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.product_images (id, product_id, storage_path, image_type, sort_order) VALUES ('prod-ww-1-img-1', 'prod-ww-1', 'https://images.unsplash.com/photo-1503602642458-232111445657', 'primary', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id, sku, name, category_id, subcategory, price, gst_percent, description, specification, primary_use_case, secondary_use_cases, material_tags, tier, speed, featured, min_order_qty, collections) VALUES ('prod-ww-2', 'VG-WW-002', 'Engraved Sheesham Barrelled Pen', 'cat-personalised-woodwork', 'Writing', 899, 18, 'A turned sheesham wood barrel pen with a hand-engraved monogram and brass fittings — an everyday writing instrument with a permanent personal touch.', '{"dimensions":"5.5\" length, turned sheesham, brass refill fittings","weight":"Artisanal spec","finish":"Buffed Natural Polish","packaging":"Kraft Tube with Sleeve","customization_options":["Monogram Engraving","Logo Burn","Personalised Gift Note"],"origin":"Artisan Clusters, India","eco_impact":"Reclaimed sheesham, renewable materials, plastic-free packaging"}'::jsonb, 'Desk Keepsakes', ARRAY['Executive Gifting','Welcome Kits','Client Souvenirs','Employee Gifting']::TEXT[], ARRAY['Wood','Metal']::TEXT[], 'Premium'::product_tier, '3-5 Days'::speed_type, false, 20, ARRAY['Premium Desk Gift Sets','Writing Instruments']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.product_images (id, product_id, storage_path, image_type, sort_order) VALUES ('prod-ww-2-img-1', 'prod-ww-2', 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace', 'primary', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id, sku, name, category_id, subcategory, price, gst_percent, description, specification, primary_use_case, secondary_use_cases, material_tags, tier, speed, featured, min_order_qty, collections) VALUES ('prod-ww-3', 'VG-WW-003', 'Personalised Wooden Coaster Set (Brass Edge)', 'cat-personalised-woodwork', 'Tableware', 749, 18, 'Four reclaimed timber coasters edged with thin brass trim, each laser-engraved with initials or a motif — a table set with family-crest warmth.', '{"dimensions":"set of 4 coasters, 4\" dia, reclaimed timber, brass edge trim","weight":"Artisanal spec","finish":"Natural Waxed Timber","packaging":"Wooden Slider Box","customization_options":["Initial Engraving","Motif Etching","Set Numbering"],"origin":"Artisan Clusters, India","eco_impact":"Reclaimed timber offcuts, brass scraps reclaimed, plastic-free box"}'::jsonb, 'Tabletop Gifting', ARRAY['Wedding Favours','Milestone Celebrations','Home Décor','Client Souvenirs']::TEXT[], ARRAY['Wood','Brass']::TEXT[], 'Essential'::product_tier, '7-10 Days'::speed_type, false, 15, ARRAY['Tableware & Drinkware']::TEXT[]) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.product_images (id, product_id, storage_path, image_type, sort_order) VALUES ('prod-ww-3-img-1', 'prod-ww-3', 'https://images.unsplash.com/photo-1553413077-190dd305871c', 'primary', 1) ON CONFLICT (id) DO NOTHING;